export const CafesJSON = [
  {
    id: 1,
    tipo: ['Tradicional'],
    nome: 'Expresso Tradicional',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    preco: '9.90',
    imagem: 'Coffee.svg',
  },
  {
    id: 2,
    tipo: ['Tradicional'],
    nome: 'Expresso Americano',
    descricao: 'Expresso diluído, menos intenso que o tradicional',
    preco: '9.90',
    imagem: 'Coffee-1.svg',
  },
  {
    id: 3,
    tipo: ['Tradicional'],
    nome: 'Expresso Cremoso',
    descricao: 'Café expresso tradicional com espuma cremosa',
    preco: '9.90',
    imagem: 'Coffee-2.svg',
  },
  {
    id: 4,
    tipo: ['Tradicional', 'Gelado'],
    nome: 'Expresso Gelado',
    descricao: 'Bebida preparada com café expresso e cubos de gelo',
    preco: '9.90',
    imagem: 'Coffee-3.svg',
  },
  {
    id: 5,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Café com Leite',
    descricao: 'Meio a meio de expresso tradicional com leite vaporizado',
    preco: '9.90',
    imagem: 'Coffee-4.svg',
  },
  {
    id: 6,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Latte',
    descricao:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    preco: '9.90',
    imagem: 'Coffee-5.svg',
  },
  {
    id: 7,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Capuccino',
    descricao:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    preco: '9.90',
    imagem: 'Coffee-6.svg',
  },
  {
    id: 8,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Macchiato',
    descricao: 'Café expresso misturado com um pouco de leite quente e espuma',
    preco: '9.90',
    imagem: 'Coffee-7.svg',
  },
  {
    id: 9,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Mocaccino',
    descricao: 'Café expresso com calda de chocolate, pouco leite e espuma',
    preco: '9.90',
    imagem: 'Coffee-8.svg',
  },
  {
    id: 10,
    tipo: ['Tradicional', 'Com leite'],
    nome: 'Chocolate Quente',
    descricao: 'Bebida feita com chocolate dissolvido no leite quente e café',
    preco: '9.90',
    imagem: 'Coffee-9.svg',
  },
  {
    id: 11,
    tipo: ['Tradicional', 'Alcoólico', 'Gelado'],
    nome: 'Cubano',
    descricao:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    preco: '9.90',
    imagem: 'Coffee-10.svg',
  },
  {
    id: 12,
    tipo: ['especial'],
    nome: 'Havaiano',
    descricao: 'Bebida adocicada preparada com café e leite de coco',
    preco: '9.90',
    imagem: 'Coffee-11.svg',
  },
  {
    id: 13,
    tipo: ['Especial'],
    nome: 'Árabe',
    descricao: 'Bebida preparada com grãos de café árabe e especiarias',
    preco: '9.90',
    imagem: 'Coffee-12.svg',
  },
  {
    id: 14,
    tipo: ['Tradicional', 'Alcoólico'],
    nome: 'Irlandês',
    descricao: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    preco: '9.90',
    imagem: 'Coffee-13.svg',
  },
];
